# / -> Client
# /api -> Server
#Annotations: Additional configurational options that are going to specify higher level configuration around the ingress object

#kubernetes.io/ingress.class: nginx  -> Telling Kubernetes, we want to create a Ingress  controller based on the nginx project

apiVersion: extensions/v1beta1
kind: Ingress
metadata: 
   name: ingress-service
   annotations:
     kubernetes.io/ingress.class: nginx
     nginx.ingress.kubernetes.io/rewrite-target: /
spec: 
  rules: 
    - http: 
       paths: 
          - path: /
            backend: 
              serviceName: client-clusterip-service
              servicePort: 3000
          - path: /api/
            backend: 
               serviceName: server-clusterip-service
               servicePort: 5000

